# Pandas

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [9]:
data = pd.read_csv("PopulationData.csv", delimiter=";", decimal=".", thousands=",")

In [10]:
data

,#,Country (or dependency),Population(2020),YearlyChange,NetChange,Density(P/Km²),Land Area(Km²),Migrants(net),Fert.Rate,Med.Age,UrbanPop %,WorldShare
0,1,China,1439323776,0.39 %,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %
1,2,India,1380004385,0.99 %,13586631,464,2973190,-532687.0,2.2,28,35 %,17.70 %
2,3,United States,331002651,0.59 %,1937734,36,9147420,954806.0,1.8,38,83 %,4.25 %
3,4,Indonesia,273523615,1.07 %,2898047,151,1811570,-98955.0,2.3,30,56 %,3.51 %
4,5,Pakistan,220892340,2.00 %,4327022,287,770880,-233379.0,3.6,23,35 %,2.83 %
...,...,...,...,...,...,...,...,...,...,...,...,...
230,231,Montserrat,4992,0.06 %,3,50,100,NaN,N.A.,N.A.,10 %,0.00 %
231,232,Falkland Islands,3480,3.05 %,103,0,12170,NaN,N.A.,N.A.,66 %,0.00 %
232,233,Niue,1626,0.68 %,11,6,260,NaN,N.A.,N.A.,46 %,0.00 %
233,234,Tokelau,1357,1.27 %,17,136,10,NaN,N.A.,N.A.,0 %,0.00 %
234,235,Vatican State,801,0.25 %,2,2003,0,NaN,N.A.,N.A.,N.A.,0.00 %

In [17]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 235 entries, 0 to 234
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   #                        235 non-null    int64
 1   Country (or dependency)  235 non-null    str
 2   Population(2020)         235 non-null    int64
 3   YearlyChange             235 non-null    str
 4   NetChange                235 non-null    int64
 5   Density(P/Km²)           235 non-null    int64
 6   Land Area(Km²)           235 non-null    int64
 7   Migrants(net)            201 non-null    float64
 8   Fert.Rate                235 non-null    str
 9   Med.Age                  235 non-null    str
 10  UrbanPop %               235 non-null    str
 11  WorldShare               235 non-null    str
dtypes: float64(1), int64(5), str(6)
memory usage: 22.2 KB

## Probleme im Datenset

Tabelle:
- Doppelter Index
- Schlechte Zeilenüberschriften

Daten selbst:
- NaN
- N.A.
- Prozentzeichen
- Datentypen

In [18]:
data

,#,Country (or dependency),Population(2020),YearlyChange,NetChange,Density(P/Km²),Land Area(Km²),Migrants(net),Fert.Rate,Med.Age,UrbanPop %,WorldShare
0,1,China,1439323776,0.39 %,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %
1,2,India,1380004385,0.99 %,13586631,464,2973190,-532687.0,2.2,28,35 %,17.70 %
2,3,United States,331002651,0.59 %,1937734,36,9147420,954806.0,1.8,38,83 %,4.25 %
3,4,Indonesia,273523615,1.07 %,2898047,151,1811570,-98955.0,2.3,30,56 %,3.51 %
4,5,Pakistan,220892340,2.00 %,4327022,287,770880,-233379.0,3.6,23,35 %,2.83 %
...,...,...,...,...,...,...,...,...,...,...,...,...
230,231,Montserrat,4992,0.06 %,3,50,100,NaN,N.A.,N.A.,10 %,0.00 %
231,232,Falkland Islands,3480,3.05 %,103,0,12170,NaN,N.A.,N.A.,66 %,0.00 %
232,233,Niue,1626,0.68 %,11,6,260,NaN,N.A.,N.A.,46 %,0.00 %
233,234,Tokelau,1357,1.27 %,17,136,10,NaN,N.A.,N.A.,0 %,0.00 %
234,235,Vatican State,801,0.25 %,2,2003,0,NaN,N.A.,N.A.,N.A.,0.00 %

In [23]:
data.drop(columns=["#"], inplace=True)  # drop kann auch Spalten löschen (deswegen columns=)

In [24]:
data

,Country (or dependency),Population(2020),YearlyChange,NetChange,Density(P/Km²),Land Area(Km²),Migrants(net),Fert.Rate,Med.Age,UrbanPop %,WorldShare
0,China,1439323776,0.39 %,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %
1,India,1380004385,0.99 %,13586631,464,2973190,-532687.0,2.2,28,35 %,17.70 %
2,United States,331002651,0.59 %,1937734,36,9147420,954806.0,1.8,38,83 %,4.25 %
3,Indonesia,273523615,1.07 %,2898047,151,1811570,-98955.0,2.3,30,56 %,3.51 %
4,Pakistan,220892340,2.00 %,4327022,287,770880,-233379.0,3.6,23,35 %,2.83 %
...,...,...,...,...,...,...,...,...,...,...,...
230,Montserrat,4992,0.06 %,3,50,100,NaN,N.A.,N.A.,10 %,0.00 %
231,Falkland Islands,3480,3.05 %,103,0,12170,NaN,N.A.,N.A.,66 %,0.00 %
232,Niue,1626,0.68 %,11,6,260,NaN,N.A.,N.A.,46 %,0.00 %
233,Tokelau,1357,1.27 %,17,136,10,NaN,N.A.,N.A.,0 %,0.00 %
234,Vatican State,801,0.25 %,2,2003,0,NaN,N.A.,N.A.,N.A.,0.00 %

In [27]:
data.set_index("Country (or dependency)", inplace=True)

In [28]:
data

,Population(2020),YearlyChange,NetChange,Density(P/Km²),Land Area(Km²),Migrants(net),Fert.Rate,Med.Age,UrbanPop %,WorldShare
Country (or dependency),,,,,,,,,,
China,1439323776,0.39 %,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %
India,1380004385,0.99 %,13586631,464,2973190,-532687.0,2.2,28,35 %,17.70 %
United States,331002651,0.59 %,1937734,36,9147420,954806.0,1.8,38,83 %,4.25 %
Indonesia,273523615,1.07 %,2898047,151,1811570,-98955.0,2.3,30,56 %,3.51 %
Pakistan,220892340,2.00 %,4327022,287,770880,-233379.0,3.6,23,35 %,2.83 %
...,...,...,...,...,...,...,...,...,...,...
Montserrat,4992,0.06 %,3,50,100,NaN,N.A.,N.A.,10 %,0.00 %
Falkland Islands,3480,3.05 %,103,0,12170,NaN,N.A.,N.A.,66 %,0.00 %
Niue,1626,0.68 %,11,6,260,NaN,N.A.,N.A.,46 %,0.00 %
Tokelau,1357,1.27 %,17,136,10,NaN,N.A.,N.A.,0 %,0.00 %
Vatican State,801,0.25 %,2,2003,0,NaN,N.A.,N.A.,N.A.,0.00 %

In [34]:
data.columns

Index(['Population(2020)', 'YearlyChange', 'NetChange', 'Density(P/Km²)',
       'Land Area(Km²)', 'Migrants(net)', 'Fert.Rate', 'Med.Age', 'UrbanPop %',
       'WorldShare'],
      dtype='str')

Spaltennamen

In [38]:
data.rename(columns={  # Hier muss ein Dict angegeben werden, in der Form: "alter Name": "Neuer Name"
    "Population(2020)": "Pop",
    "Density(P/Km²)": "Density"
}, inplace=True)

In [37]:
data

,Pop,YearlyChange,NetChange,Density,Land Area(Km²),Migrants(net),Fert.Rate,Med.Age,UrbanPop %,WorldShare
Country (or dependency),,,,,,,,,,
China,1439323776,0.39 %,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %
India,1380004385,0.99 %,13586631,464,2973190,-532687.0,2.2,28,35 %,17.70 %
United States,331002651,0.59 %,1937734,36,9147420,954806.0,1.8,38,83 %,4.25 %
Indonesia,273523615,1.07 %,2898047,151,1811570,-98955.0,2.3,30,56 %,3.51 %
Pakistan,220892340,2.00 %,4327022,287,770880,-233379.0,3.6,23,35 %,2.83 %
...,...,...,...,...,...,...,...,...,...,...
Montserrat,4992,0.06 %,3,50,100,NaN,N.A.,N.A.,10 %,0.00 %
Falkland Islands,3480,3.05 %,103,0,12170,NaN,N.A.,N.A.,66 %,0.00 %
Niue,1626,0.68 %,11,6,260,NaN,N.A.,N.A.,46 %,0.00 %
Tokelau,1357,1.27 %,17,136,10,NaN,N.A.,N.A.,0 %,0.00 %
Vatican State,801,0.25 %,2,2003,0,NaN,N.A.,N.A.,N.A.,0.00 %

Daten auslesen

In [40]:
data["Pop"]  # Normaler Index: Spalte

Country (or dependency)
China               1439323776
India               1380004385
United States        331002651
Indonesia            273523615
Pakistan             220892340
                       ...
Montserrat                4992
Falkland Islands          3480
Niue                      1626
Tokelau                   1357
Vatican State              801
Name: Pop, Length: 235, dtype: int64

In [42]:
data.loc["China"]  # Datensätze mit loc

Pop               1439323776
YearlyChange          0.39 %
NetChange            5540090
Density                  153
Land Area(Km²)       9388211
Migrants(net)      -348399.0
Fert.Rate                1.7
Med.Age                   38
UrbanPop %              61 %
WorldShare           18.47 %
Name: China, dtype: object

In [44]:
data.loc["China", "Pop":"NetChange"]  # Eine Zeile mit mehreren Spalten

Pop             1439323776
YearlyChange        0.39 %
NetChange          5540090
Name: China, dtype: object

In [45]:
data.loc["China":"Pakistan"]

,Pop,YearlyChange,NetChange,Density,Land Area(Km²),Migrants(net),Fert.Rate,Med.Age,UrbanPop %,WorldShare
Country (or dependency),,,,,,,,,,
China,1439323776,0.39 %,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %
India,1380004385,0.99 %,13586631,464,2973190,-532687.0,2.2,28,35 %,17.70 %
United States,331002651,0.59 %,1937734,36,9147420,954806.0,1.8,38,83 %,4.25 %
Indonesia,273523615,1.07 %,2898047,151,1811570,-98955.0,2.3,30,56 %,3.51 %
Pakistan,220892340,2.00 %,4327022,287,770880,-233379.0,3.6,23,35 %,2.83 %

In [46]:
data.loc["China":"Pakistan", "Pop":"Density"]

                                Pop YearlyChange  NetChange  Density
Country (or dependency)
China                    1439323776       0.39 %    5540090      153
India                    1380004385       0.99 %   13586631      464
United States             331002651       0.59 %    1937734       36
Indonesia                 273523615       1.07 %    2898047      151
Pakistan                  220892340       2.00 %    4327022      287

In [47]:
# Durchschnittsbevölkerung von diesen 5 Ländern

In [48]:
data2 = data.loc["China":"Pakistan", "Pop":"Density"]

In [49]:
data2

                                Pop YearlyChange  NetChange  Density
Country (or dependency)
China                    1439323776       0.39 %    5540090      153
India                    1380004385       0.99 %   13586631      464
United States             331002651       0.59 %    1937734       36
Indonesia                 273523615       1.07 %    2898047      151
Pakistan                  220892340       2.00 %    4327022      287

In [53]:
avg = data2["Pop"].mean()

In [55]:
data[data["Pop"] > avg]

,Pop,YearlyChange,NetChange,Density,Land Area(Km²),Migrants(net),Fert.Rate,Med.Age,UrbanPop %,WorldShare
Country (or dependency),,,,,,,,,,
China,1439323776,0.39 %,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %
India,1380004385,0.99 %,13586631,464,2973190,-532687.0,2.2,28,35 %,17.70 %

In [59]:
data.iloc[0:5, 0:3]  # Zahlen statt Texte verwenden

                                Pop YearlyChange  NetChange
Country (or dependency)
China                    1439323776       0.39 %    5540090
India                    1380004385       0.99 %   13586631
United States             331002651       0.59 %    1937734
Indonesia                 273523615       1.07 %    2898047
Pakistan                  220892340       2.00 %    4327022

In [62]:
data.sort_index(ascending=False)

,Pop,YearlyChange,NetChange,Density,Land Area(Km²),Migrants(net),Fert.Rate,Med.Age,UrbanPop %,WorldShare
Country (or dependency),,,,,,,,,,
Zimbabwe,14862924,1.48 %,217456,38,386850,-116858.0,3.6,19,38 %,0.19 %
Zambia,18383955,2.93 %,522925,25,743390,-8000.0,4.7,18,45 %,0.24 %
Yemen,29825964,2.28 %,664042,56,527970,-30000.0,3.8,20,38 %,0.38 %
Western Sahara,597339,2.55 %,14876,2,266000,5582.0,2.4,28,87 %,0.01 %
Wallis & Futuna,11239,-1.69 %,-193,80,140,NaN,N.A.,N.A.,0 %,0.00 %
...,...,...,...,...,...,...,...,...,...,...
Andorra,77265,0.16 %,123,164,470,NaN,N.A.,N.A.,88 %,0.00 %
American Samoa,55191,-0.22 %,-121,276,200,NaN,N.A.,N.A.,88 %,0.00 %
Algeria,43851044,1.85 %,797990,18,2381740,-10000.0,3.1,29,73 %,0.56 %
Albania,2877797,-0.11 %,-3120,105,27400,-14000.0,1.6,36,63 %,0.04 %
Afghanistan,38928346,2.33 %,886592,60,652860,-62920.0,4.6,18,25 %,0.50 %

In [63]:
data.sort_values("Density")

,Pop,YearlyChange,NetChange,Density,Land Area(Km²),Migrants(net),Fert.Rate,Med.Age,UrbanPop %,WorldShare
Country (or dependency),,,,,,,,,,
Greenland,56770,0.17 %,98,0,410450,NaN,N.A.,N.A.,87 %,0.00 %
Falkland Islands,3480,3.05 %,103,0,12170,NaN,N.A.,N.A.,66 %,0.00 %
Western Sahara,597339,2.55 %,14876,2,266000,5582.0,2.4,28,87 %,0.01 %
Mongolia,3278290,1.65 %,53123,2,1553560,-852.0,2.9,28,67 %,0.04 %
Australia,25499884,1.18 %,296686,3,7682300,158246.0,1.8,38,86 %,0.33 %
...,...,...,...,...,...,...,...,...,...,...
Gibraltar,33691,-0.03 %,-10,3369,10,NaN,N.A.,N.A.,N.A.,0.00 %
Hong Kong,7496981,0.82 %,60827,7140,1050,29308.0,1.3,45,N.A.,0.10 %
Singapore,5850342,0.79 %,46005,8358,700,27028.0,1.2,42,N.A.,0.08 %
Macao,649335,1.39 %,8890,21645,30,5000.0,1.2,39,N.A.,0.01 %
Monaco,39242,0.71 %,278,26337,1,NaN,N.A.,N.A.,N.A.,0.00 %

In [65]:
data["Pop"] > 10_000_000  # Welche Länder haben >10M Einwohner?

Country (or dependency)
China                True
India                True
United States        True
Indonesia            True
Pakistan             True
                    ...
Montserrat          False
Falkland Islands    False
Niue                False
Tokelau             False
Vatican State       False
Name: Pop, Length: 235, dtype: bool

In [66]:
data[data["Pop"] > 10_000_000]

,Pop,YearlyChange,NetChange,Density,Land Area(Km²),Migrants(net),Fert.Rate,Med.Age,UrbanPop %,WorldShare
Country (or dependency),,,,,,,,,,
China,1439323776,0.39 %,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %
India,1380004385,0.99 %,13586631,464,2973190,-532687.0,2.2,28,35 %,17.70 %
United States,331002651,0.59 %,1937734,36,9147420,954806.0,1.8,38,83 %,4.25 %
Indonesia,273523615,1.07 %,2898047,151,1811570,-98955.0,2.3,30,56 %,3.51 %
Pakistan,220892340,2.00 %,4327022,287,770880,-233379.0,3.6,23,35 %,2.83 %
...,...,...,...,...,...,...,...,...,...,...
Greece,10423054,-0.48 %,-50401,81,128900,-16000.0,1.3,46,85 %,0.13 %
Jordan,10203134,1.00 %,101440,115,88780,10220.0,2.8,24,91 %,0.13 %
Portugal,10196709,-0.29 %,-29478,111,91590,-6000.0,1.3,46,66 %,0.13 %
Azerbaijan,10139177,0.91 %,91459,123,82658,1200.0,2.1,32,56 %,0.13 %
Sweden,10099265,0.63 %,62886,25,410340,40000.0,1.9,41,88 %,0.13 %

In [69]:
data2.to_csv("Pop5.csv")

Fehler beheben

In [70]:
data

,Pop,YearlyChange,NetChange,Density,Land Area(Km²),Migrants(net),Fert.Rate,Med.Age,UrbanPop %,WorldShare
Country (or dependency),,,,,,,,,,
China,1439323776,0.39 %,5540090,153,9388211,-348399.0,1.7,38,61 %,18.47 %
India,1380004385,0.99 %,13586631,464,2973190,-532687.0,2.2,28,35 %,17.70 %
United States,331002651,0.59 %,1937734,36,9147420,954806.0,1.8,38,83 %,4.25 %
Indonesia,273523615,1.07 %,2898047,151,1811570,-98955.0,2.3,30,56 %,3.51 %
Pakistan,220892340,2.00 %,4327022,287,770880,-233379.0,3.6,23,35 %,2.83 %
...,...,...,...,...,...,...,...,...,...,...
Montserrat,4992,0.06 %,3,50,100,NaN,N.A.,N.A.,10 %,0.00 %
Falkland Islands,3480,3.05 %,103,0,12170,NaN,N.A.,N.A.,66 %,0.00 %
Niue,1626,0.68 %,11,6,260,NaN,N.A.,N.A.,46 %,0.00 %
Tokelau,1357,1.27 %,17,136,10,NaN,N.A.,N.A.,0 %,0.00 %
Vatican State,801,0.25 %,2,2003,0,NaN,N.A.,N.A.,N.A.,0.00 %

Strings ersetzen

In [75]:
data["YearlyChange"] = data["YearlyChange"].replace(" %", "", regex=True)

In [78]:
def fixPct(col):
    data[col] = data[col].replace(" %", "", regex=True)

In [79]:
fixPct("UrbanPop %")

In [81]:
fixPct("WorldShare")

In [82]:
data

,Pop,YearlyChange,NetChange,Density,Land Area(Km²),Migrants(net),Fert.Rate,Med.Age,UrbanPop %,WorldShare
Country (or dependency),,,,,,,,,,
China,1439323776,0.39,5540090,153,9388211,-348399.0,1.7,38,61,18.47
India,1380004385,0.99,13586631,464,2973190,-532687.0,2.2,28,35,17.70
United States,331002651,0.59,1937734,36,9147420,954806.0,1.8,38,83,4.25
Indonesia,273523615,1.07,2898047,151,1811570,-98955.0,2.3,30,56,3.51
Pakistan,220892340,2.00,4327022,287,770880,-233379.0,3.6,23,35,2.83
...,...,...,...,...,...,...,...,...,...,...
Montserrat,4992,0.06,3,50,100,NaN,N.A.,N.A.,10,0.00
Falkland Islands,3480,3.05,103,0,12170,NaN,N.A.,N.A.,66,0.00
Niue,1626,0.68,11,6,260,NaN,N.A.,N.A.,46,0.00
Tokelau,1357,1.27,17,136,10,NaN,N.A.,N.A.,0,0.00
Vatican State,801,0.25,2,2003,0,NaN,N.A.,N.A.,N.A.,0.00

In [88]:
def fixNA(col):
    data[col] = data[col].replace("N.A.", 0, regex=True)

In [89]:
fixNA("Med.Age")

In [91]:
for col in data.columns:
    fixNA(col)

In [92]:
data

,Pop,YearlyChange,NetChange,Density,Land Area(Km²),Migrants(net),Fert.Rate,Med.Age,UrbanPop %,WorldShare
Country (or dependency),,,,,,,,,,
China,1439323776,0.39,5540090,153,9388211,-348399.0,1.7,38,61,18.47
India,1380004385,0.99,13586631,464,2973190,-532687.0,2.2,28,35,17.70
United States,331002651,0.59,1937734,36,9147420,954806.0,1.8,38,83,4.25
Indonesia,273523615,1.07,2898047,151,1811570,-98955.0,2.3,30,56,3.51
Pakistan,220892340,2.00,4327022,287,770880,-233379.0,3.6,23,35,2.83
...,...,...,...,...,...,...,...,...,...,...
Montserrat,4992,0.06,3,50,100,NaN,,0,10,0.00
Falkland Islands,3480,3.05,103,0,12170,NaN,,0,66,0.00
Niue,1626,0.68,11,6,260,NaN,,0,46,0.00
Tokelau,1357,1.27,17,136,10,NaN,,0,0,0.00
Vatican State,801,0.25,2,2003,0,NaN,,0,0,0.00

NaN

In [98]:
data.isnull().value_counts()  # NaN Werte übers gesamte Datenset finden

Pop    YearlyChange  NetChange  Density  Land Area(Km²)  Migrants(net)  Fert.Rate  Med.Age  UrbanPop %  WorldShare
False  False         False      False    False           False          False      False    False       False         201
                                                         True           False      False    False       False          34
Name: count, dtype: int64

In [99]:
data["Migrants(net)"].isnull()  # Einzelne Spalte behandeln

Country (or dependency)
China               False
India               False
United States       False
Indonesia           False
Pakistan            False
                    ...
Montserrat           True
Falkland Islands     True
Niue                 True
Tokelau              True
Vatican State        True
Name: Migrants(net), Length: 235, dtype: bool

In [103]:
x = data[data["Migrants(net)"].isnull()]
data[data["Migrants(net)"].isnull()]

,Pop,YearlyChange,NetChange,Density,Land Area(Km²),Migrants(net),Fert.Rate,Med.Age,UrbanPop %,WorldShare
Country (or dependency),,,,,,,,,,
Isle of Man,85033,0.53,449,149,570,NaN,,0,53,0.00
Andorra,77265,0.16,123,164,470,NaN,,0,88,0.00
Dominica,71986,0.25,178,96,750,NaN,,0,74,0.00
Cayman Islands,65722,1.19,774,274,240,NaN,,0,97,0.00
Bermuda,62278,-0.36,-228,1246,50,NaN,,0,97,0.00
Marshall Islands,59190,0.68,399,329,180,NaN,,0,70,0.00
Northern Mariana Islands,57559,0.60,343,125,460,NaN,,0,88,0.00
Greenland,56770,0.17,98,0,410450,NaN,,0,87,0.00
American Samoa,55191,-0.22,-121,276,200,NaN,,0,88,0.00
Saint Kitts & Nevis,53199,0.71,376,205,260,NaN,,0,33,0.00
Faeroe Islands,48863,0.38,185,35,1396,NaN,,0,43,0.00
Sint Maarten,42876,1.15,488,1261,34,NaN,,0,96,0.00
Monaco,39242,0.71,278,26337,1,NaN,,0,0,0.00
Turks and Caicos,38717,1.38,526,41,950,NaN,,0,89,0.00
Saint Martin,38666,1.75,664,730,53,NaN,,0,0,0.00
Liechtenstein,38128,0.29,109,238,160,NaN,,0,15,0.00
San Marino,33931,0.21,71,566,60,NaN,,0,97,0.00
Gibraltar,33691,-0.03,-10,3369,10,NaN,,0,0,0.00
British Virgin Islands,30231,0.67,201,202,150,NaN,,0,52,0.00
Caribbean Netherlands,26223,0.94,244,80,328,NaN,,0,75,0.00
Palau,18094,0.48,86,39,460,NaN,,0,0,0.00
Cook Islands,17564,0.09,16,73,240,NaN,,0,75,0.00
Anguilla,15003,0.90,134,167,90,NaN,,0,0,0.00
Tuvalu,11792,1.25,146,393,30,NaN,,0,62,0.00
Wallis & Futuna,11239,-1.69,-193,80,140,NaN,,0,0,0.00
Nauru,10824,0.63,68,541,20,NaN,,0,0,0.00
Saint Barthelemy,9877,0.30,30,470,21,NaN,,0,0,0.00
Saint Helena,6077,0.30,18,16,390,NaN,,0,27,0.00
Saint Pierre & Miquelon,5794,-0.48,-28,25,230,NaN,,0,100,0.00
Montserrat,4992,0.06,3,50,100,NaN,,0,10,0.00
Falkland Islands,3480,3.05,103,0,12170,NaN,,0,66,0.00
Niue,1626,0.68,11,6,260,NaN,,0,46,0.00
Tokelau,1357,1.27,17,136,10,NaN,,0,0,0.00
Vatican State,801,0.25,2,2003,0,NaN,,0,0,0.00

In [104]:
x["Migrants(net)"] = 0

In [105]:
x

,Pop,YearlyChange,NetChange,Density,Land Area(Km²),Migrants(net),Fert.Rate,Med.Age,UrbanPop %,WorldShare
Country (or dependency),,,,,,,,,,
Isle of Man,85033,0.53,449,149,570,0,,0,53,0.00
Andorra,77265,0.16,123,164,470,0,,0,88,0.00
Dominica,71986,0.25,178,96,750,0,,0,74,0.00
Cayman Islands,65722,1.19,774,274,240,0,,0,97,0.00
Bermuda,62278,-0.36,-228,1246,50,0,,0,97,0.00
Marshall Islands,59190,0.68,399,329,180,0,,0,70,0.00
Northern Mariana Islands,57559,0.60,343,125,460,0,,0,88,0.00
Greenland,56770,0.17,98,0,410450,0,,0,87,0.00
American Samoa,55191,-0.22,-121,276,200,0,,0,88,0.00
Saint Kitts & Nevis,53199,0.71,376,205,260,0,,0,33,0.00
Faeroe Islands,48863,0.38,185,35,1396,0,,0,43,0.00
Sint Maarten,42876,1.15,488,1261,34,0,,0,96,0.00
Monaco,39242,0.71,278,26337,1,0,,0,0,0.00
Turks and Caicos,38717,1.38,526,41,950,0,,0,89,0.00
Saint Martin,38666,1.75,664,730,53,0,,0,0,0.00
Liechtenstein,38128,0.29,109,238,160,0,,0,15,0.00
San Marino,33931,0.21,71,566,60,0,,0,97,0.00
Gibraltar,33691,-0.03,-10,3369,10,0,,0,0,0.00
British Virgin Islands,30231,0.67,201,202,150,0,,0,52,0.00
Caribbean Netherlands,26223,0.94,244,80,328,0,,0,75,0.00
Palau,18094,0.48,86,39,460,0,,0,0,0.00
Cook Islands,17564,0.09,16,73,240,0,,0,75,0.00
Anguilla,15003,0.90,134,167,90,0,,0,0,0.00
Tuvalu,11792,1.25,146,393,30,0,,0,62,0.00
Wallis & Futuna,11239,-1.69,-193,80,140,0,,0,0,0.00
Nauru,10824,0.63,68,541,20,0,,0,0,0.00
Saint Barthelemy,9877,0.30,30,470,21,0,,0,0,0.00
Saint Helena,6077,0.30,18,16,390,0,,0,27,0.00
Saint Pierre & Miquelon,5794,-0.48,-28,25,230,0,,0,100,0.00
Montserrat,4992,0.06,3,50,100,0,,0,10,0.00
Falkland Islands,3480,3.05,103,0,12170,0,,0,66,0.00
Niue,1626,0.68,11,6,260,0,,0,46,0.00
Tokelau,1357,1.27,17,136,10,0,,0,0,0.00
Vatican State,801,0.25,2,2003,0,0,,0,0,0.00

In [108]:
data.loc[x.index] = x

In [109]:
data

,Pop,YearlyChange,NetChange,Density,Land Area(Km²),Migrants(net),Fert.Rate,Med.Age,UrbanPop %,WorldShare
Country (or dependency),,,,,,,,,,
China,1439323776,0.39,5540090,153,9388211,-348399.0,1.7,38,61,18.47
India,1380004385,0.99,13586631,464,2973190,-532687.0,2.2,28,35,17.70
United States,331002651,0.59,1937734,36,9147420,954806.0,1.8,38,83,4.25
Indonesia,273523615,1.07,2898047,151,1811570,-98955.0,2.3,30,56,3.51
Pakistan,220892340,2.00,4327022,287,770880,-233379.0,3.6,23,35,2.83
...,...,...,...,...,...,...,...,...,...,...
Montserrat,4992,0.06,3,50,100,0.0,,0,10,0.00
Falkland Islands,3480,3.05,103,0,12170,0.0,,0,66,0.00
Niue,1626,0.68,11,6,260,0.0,,0,46,0.00
Tokelau,1357,1.27,17,136,10,0.0,,0,0,0.00
Vatican State,801,0.25,2,2003,0,0.0,,0,0,0.00

In [111]:
data.ffill(inplace=True)  # Daten automatisch füllen

,Pop,YearlyChange,NetChange,Density,Land Area(Km²),Migrants(net),Fert.Rate,Med.Age,UrbanPop %,WorldShare
Country (or dependency),,,,,,,,,,
China,1439323776,0.39,5540090,153,9388211,-348399.0,1.7,38,61,18.47
India,1380004385,0.99,13586631,464,2973190,-532687.0,2.2,28,35,17.70
United States,331002651,0.59,1937734,36,9147420,954806.0,1.8,38,83,4.25
Indonesia,273523615,1.07,2898047,151,1811570,-98955.0,2.3,30,56,3.51
Pakistan,220892340,2.00,4327022,287,770880,-233379.0,3.6,23,35,2.83
...,...,...,...,...,...,...,...,...,...,...
Montserrat,4992,0.06,3,50,100,0.0,,0,10,0.00
Falkland Islands,3480,3.05,103,0,12170,0.0,,0,66,0.00
Niue,1626,0.68,11,6,260,0.0,,0,46,0.00
Tokelau,1357,1.27,17,136,10,0.0,,0,0,0.00
Vatican State,801,0.25,2,2003,0,0.0,,0,0,0.00